/**
 * Generated by `npm run stadium:promote` / `npm run stadium:rollback`.
 * Do not hand-edit entries. Only validated, reviewed, local semantic JSON is imported.
 */
import type { MfdStadiumVisualV1 } from './types.ts';
import asset0 from './assets/the-saltpan.json';

export interface RegisteredStadiumVisual {
  visual: MfdStadiumVisualV1;
  hash: string;
}

const PROMOTED: Readonly<Record<string, RegisteredStadiumVisual>> = Object.freeze({
  "the-saltpan": { visual: asset0 as unknown as MfdStadiumVisualV1, hash: "v1-fnv1a64-7f3a0c87806af081" },
});

export function resolveStadiumVisual(stadiumId: string): RegisteredStadiumVisual | null {
  return PROMOTED[stadiumId] ?? null;
}

export const PROMOTED_STADIUM_VISUAL_IDS: readonly string[] = Object.freeze(
  Object.keys(PROMOTED).sort(),
);
