import { chromium } from 'playwright';
const url = 'http://127.0.0.1:5202/probe-editor/index.html';
const R = []; const check = (n,p,d='') => { R.push(p); console.log(`${p?'PASS':'FAIL'}  ${n.padEnd(54)} ${d}`); };
const b = await chromium.launch({ args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const page = await b.newPage({ viewport: { width: 1600, height: 950 } });
const errors = []; page.on('console', m => { if (m.type()==='error') errors.push(m.text()); });
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 120000 });
await page.waitForFunction(() => !!window.GO, null, { timeout: 180000 });
await page.evaluate(() => { localStorage.removeItem('go.save.v1'); window.GO.reset('practice'); });
await page.waitForTimeout(400);
check('practice mounts', await page.evaluate(() => window.GO.currentScreen === 'practice'));
const rows = await page.evaluate(() => [...document.querySelectorAll('#ui-root .go-opt')].map(r => r.querySelector('.go-opt-label')?.textContent ?? ''));
check('setup panel exposes every required control',
  ['DRILL','YOU PLAY','YOUR TEAM','OPPOSING TEAM','BALL ON','DOWN','OFFENSIVE PLAY','DEFENSIVE PLAY','REPEAT SPOT','DEV OVERLAY'].every(k => rows.includes(k)), rows.join(','));
await page.evaluate(async () => {
  const R2 = () => [...document.querySelectorAll('#ui-root .go-opt')];
  const hit = (l,n) => { const r = R2().find(x => x.querySelector('.go-opt-label')?.textContent === l); for (let i=0;i<n;i++) r.querySelectorAll('.go-opt-arrow')[1].click(); };
  hit('DEV OVERLAY',1); await new Promise(r=>requestAnimationFrame(r));
  hit('BALL ON',3);     await new Promise(r=>requestAnimationFrame(r));
  hit('DOWN',2);        await new Promise(r=>requestAnimationFrame(r));
});
const chosen = await page.evaluate(() => { const R2=[...document.querySelectorAll('#ui-root .go-opt')];
  const v=l=>R2.find(x=>x.querySelector('.go-opt-label')?.textContent===l)?.querySelector('.go-opt-value')?.textContent;
  return { ball:v('BALL ON'), down:v('DOWN'), dev:v('DEV OVERLAY') }; });
check('option rows change value', chosen.ball==='OWN 40' && chosen.down==='3RD & 30' && chosen.dev==='ON', JSON.stringify(chosen));
await page.evaluate(() => [...document.querySelectorAll('#ui-root .go-btn')].find(x=>x.textContent.trim()==='START DRILL').click());
await page.waitForFunction(() => !!window.GO.match, null, { timeout: 120000 });
await page.waitForTimeout(2500);
const live = await page.evaluate(() => { const m=window.GO.match; return { mode:m.config.mode, phase:m.state.phase, los:m.state.losZ, down:m.state.down, fd:m.state.firstDownZ, freeze:m.world.freezeDefense, off:m.world.offensePlay?.name, def:m.world.defensePlay?.name, tick:m.world.tick }; });
check('drill launches a PRACTICE match', live.mode === 'PRACTICE', JSON.stringify(live));
check('kickoff skipped; armed at the chosen down and spot', live.los === 40 && live.down === 3 && live.fd === 70);
check('the chosen calls are the ones on the field', !!live.off && !!live.def, `${live.off} vs ${live.def}`);
check('VERSUS drill leaves the defence live', live.freeze === false);
check('dev overlay present and populated', await page.evaluate(() => { const t=document.body.innerText; return t.includes('DEV OVERLAY')&&t.includes('LOS')&&t.includes('PHASE')&&t.includes('BALL'); }));
await page.waitForTimeout(8000);
const ran = await page.evaluate(() => ({ tick:window.GO.match.world.tick, finished:window.GO.match.state.finished, q:window.GO.match.state.quarter, clock:window.GO.match.state.clockTicks, reps:(document.body.innerText.match(/REP (\d+)/)||[])[1] }));
check('drill runs plays without stalling or ending', ran.tick > 300 && !ran.finished, JSON.stringify(ran));
check('practice holds the clock so the match never expires', ran.q === 1 && ran.clock > 0);
await page.evaluate(() => { const m=window.GO.match; m.state.losZ=71; m.state.down=2; });
await page.evaluate(async () => { window.dispatchEvent(new KeyboardEvent('keydown',{code:'Backspace',bubbles:true}));
  await new Promise(r=>requestAnimationFrame(r)); window.dispatchEvent(new KeyboardEvent('keyup',{code:'Backspace',bubbles:true})); await new Promise(r=>requestAnimationFrame(r)); });
await page.waitForTimeout(400);
const rst = await page.evaluate(() => ({ los:window.GO.match.state.losZ, down:window.GO.match.state.down, fd:window.GO.match.state.firstDownZ, phase:window.GO.match.state.phase }));
check('BACK re-arms the same down at the same spot', rst.los===40 && rst.down===3 && rst.fd===70, JSON.stringify(rst));
await page.evaluate(async () => { window.GO.match.state.losZ = 12;
  [...document.querySelectorAll('#ui-root .go-btn')].find(x=>x.textContent.trim()==='RESET').click(); await new Promise(r=>requestAnimationFrame(r)); });
check('the on-screen RESET button works too', await page.evaluate(() => window.GO.match.state.losZ === 40));
await page.evaluate(async () => { window.dispatchEvent(new KeyboardEvent('keydown',{code:'Escape',bubbles:true}));
  await new Promise(r=>requestAnimationFrame(r)); window.dispatchEvent(new KeyboardEvent('keyup',{code:'Escape',bubbles:true})); });
await page.waitForTimeout(600);
check('PAUSE opens the pause menu', await page.evaluate(() => window.GO.currentScreen === 'pause'));
await page.evaluate(() => window.GO.back());
await page.waitForTimeout(700);
check('resuming returns to the live drill, not the setup panel',
  await page.evaluate(() => window.GO.currentScreen==='practice' && !!window.GO.match && document.body.innerText.includes('REP')));
await page.evaluate(async () => { window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyH',bubbles:true}));
  await new Promise(r=>requestAnimationFrame(r)); window.dispatchEvent(new KeyboardEvent('keyup',{code:'KeyH',bubbles:true})); });
await page.waitForTimeout(700);
check('HIDE PLAY exits the drill back to the setup panel',
  await page.evaluate(() => !window.GO.match && document.body.innerText.includes('PRACTICE FIELD')));
check('no console errors', errors.length === 0, errors.slice(0,3).join(' // '));
await b.close();
console.log(`\n${R.filter(Boolean).length}/${R.length} checks passed`);
process.exit(R.every(Boolean) ? 0 : 1);
